"""Regenerate the approved SVG artwork + matching sampled collision outlines. Python stdlib only."""
from pathlib import Path
import re, json, xml.etree.ElementTree as ET
root = Path(__file__).resolve().parents[1]
html = (root / 'docs/animal-tower/index.html').read_text()
groups = ET.fromstring('<defs>' + html.split('<defs>')[1].split('</defs>')[0] + '</defs>')
labels = dict(re.findall(r"\['([^']+)','([^']+)'", html))
items = []
for g in groups:
    path = g[0].get('d')
    tokens = re.findall(r'[MLQZ]|-?\d+(?:\.\d+)?', path)
    vertices, at, i = [], (0, 0), 0
    while i < len(tokens):
        op = tokens[i]; i += 1
        if op in ('M', 'L'):
            at = tuple(float(v) for v in tokens[i:i+2]); i += 2
            vertices.append(at)
        elif op == 'Q':
            cx, cy, x, y = map(float, tokens[i:i+4]); i += 4
            ax, ay = at
            for j in range(1, 6):
                t = j/5; u = 1-t
                vertices.append((round(u*u*ax+2*u*t*cx+t*t*x, 3), round(u*u*ay+2*u*t*cy+t*t*y, 3)))
            at = x, y
        elif op != 'Z':
            raise ValueError(op)
    # Remove adjacent duplicate vertices, which break polygon decomposition.
    vertices = [v for j,v in enumerate(vertices) if j == 0 or v != vertices[j-1]]
    if vertices[-1] == vertices[0]: vertices.pop()
    marks = []
    for el in list(g)[1:]:
        mark = {'tag': el.tag, **el.attrib}
        marks.append(mark)
    items.append({'id':g.get('id'), 'label':labels[g.get('id')], 'outline':path, 'vertices':vertices, 'marks':marks})
prefix = '''// Generated by scripts/import-tower-art.py from docs/animal-tower/index.html.
export interface AnimalMark { tag: string; [key: string]: string; }
export interface AnimalArt { id: string; label: string; outline: string; vertices: number[][]; marks: AnimalMark[]; }
export const ANIMALS: AnimalArt[] = '''
(root / 'src/renderer/games/tower/animals.ts').write_text(prefix + json.dumps(items, ensure_ascii=False, separators=(',', ':')) + ';\n')
print(f'Generated {len(items)} animals')
